rdap:
    # A list of RDAP authorities may be configured ahead of time, if
    # required.  Each authority has a name, an optional list of
    # aliases, a list of RDAP servers used as reference in the IANA bootstrap
    # file and a routing section. The routing section have an optional action
    # (if no action is defined the defaultAction value will be used), a routing
    # target and a optional fallback authority for queries resulting in 404
    # responses (not found).
    authorities:
        - name: apnic
          routing:
              action: proxy
              target: https://rdap.apnic.net/
          ianaBootstrapRefServers:
              - https://rdap.apnic.net
              - http://rdap.apnic.net

        - name: ripe
          aliases:
              - ripencc
          routing:
            action: redirect
            target: https://rdap.db.ripe.net
          ianaBootstrapRefServers:
              - https://rdap.db.ripe.net/

        - name: afrinic
          routing:
            action: redirect
            target: https://rdap.afrinic.net/rdap/
          ianaBootstrapRefServers:
              - http://rdap.afrinic.net/rdap/

        - name: arin
          routing:
            action: redirect
            target: https://rdap.arin.net/registry/
          ianaBootstrapRefServers:
              - https://rdap.arin.net/registry/
              - http://rdap.arin.net/registry/

        - name: lacnic
          routing:
            action: redirect
            target: https://rdap.lacnic.net/rdap/
            notFoundFallbackAuthority: apnic
          ianaBootstrapRefServers:
              - https://rdap.lacnic.net/rdap/

    routing:
        # The default routing action to take for authorities. Accepts either
        # redirect or proxy.
        defaultAction: redirect

        # Allows rdap-ingressd to proxy unroutable requests to a
        # default authority. The name of the authority specified here
        # can be null or a name specified in the 'authorities' section
        # above. All requests to this authority are proxied.
        defaultAuthority: null

    # List of default notices that are sent with RDAP responses from this 
    # server.
    # Each notice in the list takes on the following form
    # - title: Optional title for the notice
    # - description: # Array of description lines
    #     - description line 1
    #     - description line 2
    # - links: # Array of link object for the notice
    #    - href: Non optional URL ref for the link
    #      rel: Optional relation type
    #      type: link type
    notices: []

    scraping:
        scrapers:
            # Individual scrapers available in rdap-ingressd can be enabled and
            # disabled. It's also possible to specify the property baseURI for
            # each scraper to change the location where data is fetched from.
            # The special "custom" scraper may be used to fetch multiple sources
            # of delegated stats data.
            iana:
                enabled: true
            nro:
                enabled: true
                baseURI: https://labs.apnic.net/delegated-nro-extended
            custom:
                enabled: false
                entries:
                    - name: nir
                      uri:
        config:
            # Order in which scrapers are run.
            order:
            - iana
            - nro
            #- custom
