
rdap:
    authorities:
        - name: apnic
          servers:
              - https://rdap.apnic.net
              - http://rdap.apnic.net

        - name: ripe
          aliases:
              - ripencc
          servers:
              - https://rdap.db.ripe.net/

        - name: afrinic
          servers:
              - https://rdap.afrinic.net/rdap/
              - http://rdap.afrinic.net/rdap/

        - name: arin
          servers:
              - https://rdap.arin.net/registry
              - http://rdap.arin.net/registry

        - name: lacnic
          servers:
              - https://rdap.lacnic.net/rdap/

    scraping:
        scrapers:
            iana:
                enabled: true
            nro:
                enabled: true
        config:
            order:
                - iana
                - nro

endpoints:
    enabled: false
    pause:
        enabled: false
    restart:
        enabled: false
    resume:
        enabled: false
    env:
        enabled: false
        post:
            enabled: false

zuul:
    routes:
        autnum:
            path: /autnum/**
            stripPrefix: false
        domain:
            path: /domain/**
            stripPrefix: false
        entity:
            path: /entity/**
            stripPrefix: false
        help:
            path: /help
            stripPrefix: false
        ip:
            path: /ip/**
            stripPrefix: false
        nameserver:
            path: /nameserver/**
            stripPrefix: false
