
endpoints:
    enabled: false
    health:
        enabled: true
    pause:
        enabled: false
    restart:
        enabled: false
    resume:
        enabled: false
    env:
        enabled: false
        post:
            enabled: false

zuul:
    routes:
        autnum:
            path: /autnum/**
            stripPrefix: false
        domain:
            path: /domain/**
            stripPrefix: false
        entity:
            path: /entity/**
            stripPrefix: false
        help:
            path: /help
            stripPrefix: false
        ip:
            path: /ip/**
            stripPrefix: false
        nameserver:
            path: /nameserver/**
            stripPrefix: false

spring.profiles.include: 'rdap'
