
rdap:
     #If it is known a head of time a list of pre defined rdap authorities can
     #be configured. Each authority takes the form of:
     # name: <primary_authority_name>
     # aliases: # Optional list of aliases this authority can be known as.
     # servers: # List of one or more rdap server URI's for the authority
    authorities:
        - name: apnic
          servers:
              - https://rdap.apnic.net
              - http://rdap.apnic.net

        - name: ripe
          aliases:
              - ripencc
          servers:
              - https://rdap.db.ripe.net/

        - name: afrinic
          servers:
              - https://rdap.afrinic.net/rdap/
              - http://rdap.afrinic.net/rdap/

        - name: arin
          servers:
              - https://rdap.arin.net/registry
              - http://rdap.arin.net/registry

        - name: lacnic
          servers:
              - https://rdap.lacnic.net/rdap/

    routing:
        # The default routing action to take for authorities. Accepts either
        # redirect or proxy
      defaultAction: redirect

        # Allows rdap-ingressd to proxy unroutable requests to a default
        # authority. The name of the authority specificed here can be null or
        # a name specified in authorities above. All requests to this authority
        # are proxied.
      defaultAuthority: null

    scraping:
        scrapers:
            # Individual scrapers available in rdap-ingressd can be enabled and
            # disabled
            iana:
                enabled: true
            nro:
                enabled: true
        config:
            # Order in which scrapers are run
            order:
                - iana
                - nro
