replicaCount: 1

image:
  repository: null
  tag: null
  pullPolicy: IfNotPresent

livenessProbe:
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 5
  initialDelaySeconds: 60
  timeoutSeconds: 5
readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  initialDelaySeconds: 60
  timeoutSeconds: 5
  successThreshold: 1

strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

podDisruptionBudget: {}
  #minAvailable: 0
  #maxUnavailable: 0

# Controls the autoscaling behaviour of ingressd, disabled by default
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

proxy:
  enabled: false
  httpHost: ""
  httpPort: ""
  httpsHost: ""
  httpsPort: ""
  noProxy: []

# Allow extra JVM options to be set
javaOpts: ~

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

prometheus:
  serviceMonitor:
    # Create prometheus-operator ServiceMonitor
    enabled: false
    # Interval at which the metrics endpoint is scraped
    interval: 30s
    # Path on service which exposes metrics
    path: /prometheus
    # Alternative namespace to install the ServiceMonitor in
    namespace: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Allow configuring the prometheus rule for monitoring scrapers. Disabled by default.
scraperOutdatedPrometheusRule:
  enabled: false
  message: RDAP Ingressd scraper outdated
  description: The scraper {{ $labels.scraper }} in the pod {{ $labels.kubernetes_pod_name }} is outdated.
  labels:
    channel: email
    team: registry
    severity: warning

# Additional YAML put into the application's `rdap` profile configuration file as-is.
application_rdap:
    # See https://gitlab.xyz.apnic.net/sw/rdap/rdap-ingressd for documentation over
    # config file.
    rdap:
      # A list of RDAP authorities may be configured ahead of time, if
      # required.  Each authority has a name, an optional list of
      # aliases, a list of RDAP servers used as reference in the IANA bootstrap
      # file and a routing section. The routing section have an optional action
      # (if no action is defined the defaultAction value will be used), a routing
      # target and a optional fallback authority for queries resulting in 404
      # responses (not found).
      authorities:
        - name: apnic
          routing:
            action: proxy
            target: http://rdapd:8080/
          ianaBootstrapRefServers:
            - https://rdap.apnic.net
            - http://rdap.apnic.net

        - name: ripe
          aliases:
            - ripencc
          routing:
            action: redirect
            target: https://rdap.db.ripe.net
          ianaBootstrapRefServers:
            - https://rdap.db.ripe.net/

        - name: afrinic
          routing:
            action: redirect
            target: https://rdap.afrinic.net/rdap/
          ianaBootstrapRefServers:
            - https://rdap.afrinic.net/rdap/
            - http://rdap.afrinic.net/rdap/

        - name: arin
          routing:
            action: redirect
            target: https://rdap.arin.net/registry/
          ianaBootstrapRefServers:
            - https://rdap.arin.net/registry/
            - http://rdap.arin.net/registry/

        - name: lacnic
          routing:
            action: redirect
            target: https://rdap.lacnic.net/rdap/
          ianaBootstrapRefServers:
            - https://rdap.lacnic.net/rdap/
      routing:
        # Default routing action for authorities
        defaultAction: redirect
        # Default authority for non routable requests
        defaultAuthority: apnic
      notices:
      - title: Terms and Conditions
        description:
        - This is the APNIC RDAP query service. The objects are in RDAP format.
        links:
        - href: http://www.apnic.net/db/dbcopyright.html
          rel: terms-of-service
          type: text/html
      scraping:
        scrapers:
          iana:
            enabled: true
          nro:
            enabled: true
        config:
          order:
          - iana
          - nro
