apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "application.fullname" . }}
    helm.sh/chart: {{ include "application.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application-rdap.yml: |2
{{- with .Values.application_rdap }}
{{ toYaml . | indent 4 }}
{{- end }}
