apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rdap-ingressd.fullname" . }}
  labels:
    {{- include "rdap-ingressd.labels" . | nindent 4 }}
data:
  application-rdap.yml: |2
    {{- with .Values.application_rdap }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
