apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    chart: {{ template "application.chart" . }}
    app: {{ template "application.fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchlabels:
      chart: {{ template "application.chart" . }}
      app: {{ template "application.fullname" . }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        chart: {{ template "application.chart" . }}
        app: {{ template "application.fullname" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "application.fullname" . }}
          image: {{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/application-rdap.yml
              name: rdapd-config
              subPath: application-rdap.yml
      volumes:
        - name: rdapd-config
          configMap:
            name: {{ template "application.fullname" . }}
