{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rdap-ingressd.fullname" . }}
  labels:
    {{- include "rdap-ingressd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rdap-ingressd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- toYaml .Values.podDisruptionBudget | trim | nindent 2 }}
{{- end }}
