{{- if .Values.scraperOutdatedPrometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-operator
    role: alert-rules
  name: {{ include "rdap-ingressd.name" . }}-scraper-outdated
spec:
  groups:
    - name: registry
      rules:
        - alert: RdapIngressdScraperOutdated
          annotations:
            message: {{ .Values.scraperOutdatedPrometheusRule.message }}
            description: {{ .Values.scraperOutdatedPrometheusRule.description }}
          expr: rdap_ingressd_scraper_status{job={{ .Release.Name | quote }}}==1 or time() - rdap_ingressd_scraper_last_successful_update_datetime > 60 * 60 * 24
          labels:
            {{- toYaml .Values.scraperOutdatedPrometheusRule.labels | nindent 12 }}
{{- end }}