apiVersion: v1
kind: Service
metadata:
  name: {{ include "rdap-ingressd.fullname" . }}
  labels:
    {{- include "rdap-ingressd.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "rdap-ingressd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}
