service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  hosts: [] #defined in pipeline

resources:
  requests:
    memory: "2048Mi"
    cpu: "1"
  limits:
    memory: "2048Mi"
    cpu: "2"

javaOpts: -Xms1000m -Xmx1800m

proxy:
  enabled: false

scraperOutdatedPrometheusRule:
  enabled: true
  message: TEST - RDAP Ingressd scraper outdated
