service:
  type: NodePort
  port: 8080
ingress:
  enabled: true
  hosts: [] #defined in pipeline
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "2"
proxy:
  enabled: true
  httpHost: squid-proxy.apnic.net
  httpPort: 3128
  httpsHost: squid-proxy.apnic.net
  httpsPort: 3128
  noProxy: []
