service:
  type: NodePort
  port: 8080
ingress:
  enabled: true
  hosts: [] #defined in pipeline
resources:
  requests:
    memory: "1024Mi"
    cpu: "1"
  limits:
    memory: "1024Mi"
    cpu: "2"
proxy:
  enabled: false
